# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode13.4
language: objective-c
cache: cocoapods
podfile: Example/Podfile
xcode_workspace: Example/ODStringify_Example.xcworkspace
xcode_scheme: ODStringify_Example
xcode_destination: platform=iOS Simulator,OS=14.5,name=iPhone X
before_install:
- gem install cocoapods xcpretty # Since Travis is not always on latest version
- pod install --project-directory=Example
script:
# - set -o pipefail && xcodebuild  -enableCodeCoverage YES -workspace Example/ODStringify_Example.xcworkspace -scheme ODStringify_Example -destination 'platform=iOS Simulator,OS=14.5' ONLY_ACTIVE_ARCH=NO test | xcpretty
- pod lib lint
